In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/vgsales.csv", index_col=0)
df.head(15)

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Rank,,,,,,,,,,
1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
6,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26
7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
8,Wii Play,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62
10,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31
11,Nintendogs,DS,2005.0,Simulation,Nintendo,9.07,11.00,1.93,2.75,24.76
12,Mario Kart DS,DS,2005.0,Racing,Nintendo,9.81,7.57,4.13,1.92,23.42
13,Pokemon Gold/Pokemon Silver,GB,1999.0,Role-Playing,Nintendo,9.00,6.18,7.20,0.71,23.10
14,Wii Fit,Wii,2007.0,Sports,Nintendo,8.94,8.03,3.60,2.15,22.72
15,Wii Fit Plus,Wii,2009.0,Sports,Nintendo,9.09,8.59,2.53,1.79,22.00

In [2]:
df.info()
df.shape
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 16598 entries, 1 to 16600
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          16449 non-null  object
 1   Platform      16449 non-null  object
 2   Year          16180 non-null  float64
 3   Genre         16449 non-null  object
 4   Publisher     16392 non-null  object
 5   NA_Sales      16449 non-null  float64
 6   EU_Sales      16449 non-null  float64
 7   JP_Sales      16449 non-null  float64
 8   Other_Sales   16449 non-null  float64
 9   Global_Sales  16449 non-null  float64
dtypes: float64(6), object(4)
memory usage: 1.4+ MB

,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16180.000000,16449.000000,16449.000000,16449.000000,16449.000000,16449.000000
mean,2006.392213,0.266135,0.147561,0.078081,0.048350,0.540407
std,5.840225,0.820100,0.507443,0.310414,0.189393,1.561501
min,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,2010.000000,0.240000,0.110000,0.040000,0.040000,0.480000
max,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [3]:
df.describe(include='object')

                               Name Platform   Genre        Publisher
count                         16449    16449   16449            16392
unique                        11392       31      12              573
top     Need for Speed: Most Wanted      PS2  Action  Electronic Arts
freq                             12     2143    3290             1351

In [4]:
print("missing values sebelum cleaning")
df.isnull().sum()

missing values sebelum cleaning

Name            149
Platform        149
Year            418
Genre           149
Publisher       206
NA_Sales        149
EU_Sales        149
JP_Sales        149
Other_Sales     149
Global_Sales    149
dtype: int64

In [5]:
df['Year'] = df['Year'].fillna(df['Year'].median())
df['Publisher'] = df['Publisher'].fillna('Unknown')
df = df.dropna()
df["Year"] = df['Year'].astype(int)

In [6]:
print("missing value setelah cleaning")
df.isnull().sum()

missing value setelah cleaning

Name            0
Platform        0
Year            0
Genre           0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64

In [7]:
df[df.duplicated(keep=False)]

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Rank,,,,,,,,,,
15000,Wii de Asobu: Metroid Prime,Wii,2007,Shooter,Nintendo,0.0,0.0,0.02,0.0,0.02
15002,Wii de Asobu: Metroid Prime,Wii,2007,Shooter,Nintendo,0.0,0.0,0.02,0.0,0.02

In [8]:
df = df.drop_duplicates()

In [15]:
df.to_csv("../data/processed/vgsales_cleaned.csv", index=False)